from django.conf.urls import patterns,url
from feed import UltimosProblemas

urlpatterns = patterns('apps.sitio.views',
    url(r'^$', 'index_view'),
    url(r'^envios/$', 'envios_view'),
    url(r'^concursos/$', 'concursos_view'),
    url(r'^concurso/(?P<id_concurso>\d+)/$', 'concurso_view'),
    url(r'^concurso/(?P<id_concurso>\d+)/ranking$', 'concurso_ver_ranking'),
    url(r'^concurso/(?P<id_concurso>\d+)/consultas$', 'concurso_ver_consultas'),
    url(r'^concurso/(?P<id_concurso>\d+)/problema/(?P<id_problema>\d+)$', 'problema_concurso'),
    url(r'^medallero/$', 'medallero_view'),
    url(r'^faqs/$', 'faqs_view'),
    url(r'^wiki/$', 'wiki_view'),
    url(r'^ayuda/$', 'ayuda_view'),
    url(r'^privacidad/$', 'privacidad_view'),
    url(r'^perfil/$', 'perfil_view'),
    url(r'^registro/$', 'registro_view'),
    url(r'^mis_soluciones/$', 'mis_soluciones_view'),
    url(r'^usuarios/$', 'usuarios_view'),
    url(r'^usuario/(?P<id_usuario>\d+)$', 'usuario_view'),
    url(r'^problemas/$', 'problemas_view'),
    url(r'^problema/(?P<nombre_administrativo>[a-zA-Z_-]+)/$', 'problema_detalle'),
    url(r'^auth/login/$', 'login'),
    url(r'^auth/logout/$', 'logout'),
    url(r'^auth/change_pass/$', 'external_change_pass'),
    url(r'^auth/change_pass_internal/$', 'internal_change_pass'),
    url(r'^baja/$', 'baja'),
    url(r'^problemas/feed/$', UltimosProblemas()),
)
