from django.conf.urls import patterns,url

urlpatterns = patterns('apps.api.views',
    url(r'^$', 'index'),
    url(r'^mundo_ejemplo/(?P<id_problema>\d+)/$', 'mundo_ejemplo'),
    url(r'^mundo_ejemplo_solucion/(?P<id_problema>\d+)/$', 'mundo_ejemplo_solucion'),
    url(r'^concurso/(?P<id_concurso>\d+)/mundo_ejemplo/(?P<id_problema>\d+)/$', 'mundo_ejemplo_concurso'),
    url(r'^concurso/(?P<id_concurso>\d+)/mundo_ejemplo_solucion/(?P<id_problema>\d+)/$', 'mundo_ejemplo_solucion_concurso'),
    url(r'^nombres_escuela/$', 'nombres_escuela'),
    url(r'^nombres_asesores/$', 'nombres_asesores'),
    url(r'^existe_usuario/(?P<nombre_usuario>\w+)/$', 'existe_usuario'),
    url(r'^descarga_codigo/(?P<id_envio>\d+)/$', 'descarga_codigo'),
    url(r'^problema/(?P<id_problema>\d+)/mundo/$', 'descarga_mundo'),
    url(r'^envio/(?P<id_envio>\d+)/$', 'envio'),
    url(r'^envio/(?P<id_envio>\d+)/concurso/(?P<id_concurso>\d+)/$', 'envio'),
    url(r'^hacer_consulta/$', 'hacer_consulta'),
    url(r'^responde_consulta/$', 'responde_consulta'),
    url(r'^busca_consultas/(?P<id_concurso>\d+)/$', 'busca_consultas'),
    url(r'^consultas/(?P<id_concurso>\d+)/problema/(?P<id_problema>\d+)/$', 'consultas'),
    url(r'^ranking_csv/(?P<id_concurso>\d+)/$', 'ranking_csv'),
    url(r'^aclaracion/(?P<id_concurso>\d+)/$', 'aclaracion'),
    url(r'^obten_nombre_asesor/(?P<id_asesor>\d+)/$', 'obten_nombre_asesor'),
)
